//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complex_service
    {
        public int Id_complex { get; set; }
        public int Id_service { get; set; }
        public int Id_type_device { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Type_device Type_device { get; set; }
    }
}
