//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Registration_for_the_provision_of_services = new HashSet<Registration_for_the_provision_of_services>();
        }
    
        public int Id_employee { get; set; }
        public string Second_name { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime Date_of_birthday { get; set; }
        public string Mail { get; set; }
        public string Phone_number { get; set; }
        public int Id_post { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration_for_the_provision_of_services> Registration_for_the_provision_of_services { get; set; }
    }
}
