//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenterIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration_for_the_provision_of_services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration_for_the_provision_of_services()
        {
            this.Purchase_structure = new HashSet<Purchase_structure>();
        }
    
        public int Id_record { get; set; }
        public int Id_sevice { get; set; }
        public int Id_device { get; set; }
        public int Id_employee { get; set; }
        public System.DateTime acceptance_date_device { get; set; }
        public string Work_plan { get; set; }
        public System.DateTime Date_start_work { get; set; }
        public System.DateTime Date_end_work { get; set; }
        public int Id_закупки { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_structure> Purchase_structure { get; set; }
        public virtual Service Service { get; set; }
    }
}
